var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "          o                                                                     ",
   "                                                 o       x                      ",
   "         xxx                                             x                      ",
   " x                                               x       x                      ",
   "o                                                        x                      ",
   "                                                       x x                      ",
   "x                                           o            x                      ",
   "                                                         x                      ",
   "                           o      xxx      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   o  ",
   "o xx                                                                            ",
   "  x                       xxx                                                   ",
   "x x  @                                                                          ",
   "  x               xxx                              o                            ",
   "  x                        x                    x                               ",
   " xxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!xxxxxxx                         ",
   "o                           x!!!!!!!!!!!!!!!!!!x         xx                     ",
   "                             x!!!!!!!!!!!!!!!!x                xx               ",
   "x                             xxxxxxxxxxxxxxxx                       xx         ",
   "          o           o             o             o                        xxxxx",
   "                                                       !!!!!!!!!!!!!!!!!!!!!!!!!",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  ["!                                                                                          x                      ",
   "! o                                                                                        x                 x!!!x",
   "!                             o                      o                                     x                   v  ",
   "!xxx            o                   x                                                      x                      ",
   "!                       xxxxxxxxxxxx!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx        o            x                      ",
   "!      x       xxx                  v                                                      xxxx!!   !!xxx         ",
   "!                                                                            xxx            xxx!!   !!xxx    xx   ",
   "!                                                        o        o                         xxx!! o !!xxx         ",
   "!                                                                                           xxx!!   !!xxx         ",
   "!                      xxx                     xxx      xxx      xxx      xxx               xxx!!   !!xxx       xx",
   "!                                x!! !!xx        x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!             xxx!!   !!xxx         ",
   "!                               !xxx xx          xxxxxxxxxxxxxxxxxxxxxxxxxxxxxv            xxx!!   !!xxx          ",
   "!                xxx          !!!x  V                                                      xxx!!   !!xxx     xx   ",
   "!                          !!!!!!x                                                         xxx!!   !!xxx          ",
   "!          xxx          !!!!!!!!!x                                                         xxx!! o !!xxx          ",
   "!       xxxxxxxxxxxxxxxxxxxxxxxxxx    xxxxx                                                xxx!!   !!xxx        xx",
   "!       x                             m    x                                               xxx!!   !!xxx          ",
   "!!x               o      o                 x                              xxx     o        xxx!!   !!xxx          ",
   "!!!x                                     o x                      o                         xxx!!   !!xxx    xx   ",
   "!!!!    o                                  xxx    o                              xxx        xxx!! o !!xxx         ",
   "!!!!!   x  |  xx  |  xx  |  xx     x    xxxx                    o                           xxx!!   !!xxx         ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x     xxx           xxx                                      x       xx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxvxxxxxx                                              x             x         ",
   "                                                       xxx                                xxxxxxxxxxxxxxx         ",
   "                                                                                                             xx   ",
   "                                                                                                                  ",
   "                                                                                 xxx                              ",
   "   @       o      xxx       o                o                          xxx                              xxxxxx xx",
   "          xxx         x              =              x     xxx      o                      o      xxx              ",
   "  xxx                 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx             xxx                    xxx                      ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["     x!                                                                x                             ",
   "     x!     v                                                          x                             ",
   "     x!                                                      m         x                             ",
   "     x!                                 m                              x                             ",
   "     x!                        m                                       x      2   4   5   1  3  6    ",
   "     x!                                         m                      x                             ",
   "     x!             !                                                                                ",
   "     x!            !xxxxxxxxx xxxxxxxxxxxxx xxxxxxxxxxxx xxxxxxxxxxxx      xxxxxxxxxxxxxxxxxxxxxxxxxx",
   "     x!            !x       xxx           xxx          xxx          xxxxxxxx                         ",
   "     x!        xxx !x       x   3      2                                x                            ",
   "     x!            !x       x                                           x                            ",
   "     x!            !x       x                                           x                            ",
   "     x! xxx        !x       xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx          x                            ",
   "     x!            !x       x                                       xxxxx                            ",
   "     x!            !x       xmm                                      x                               ",
   "     x!        xxx !x       xmm                                      x                               ",
   "     x!            !x       xxxxx                                xxxxm                               ",
   "     x!            !x           x                        xxx     x                                   ",
   "     x! xxx        !x           x              xxxxx             x                                   ",
   "     x!            !x           x               m                x                                   ",
   "     x!            !x           x                                x                                   ",
   "     x!        xxx !x           x     xxx                        x          xxxxxxxxxxxxxx           ",
   "     x!            !x           x                                x          x            x           ",
   "     x!            !x           x              xxxxx             x          x            x           ",
   "     x! xxx        !x           x                                x          x            x           ",
   "     x!            !x           x                                x          x            x           ",
   "     x!            !x           x                        xxx     x          x            x           ",
   "     x!        xxx !x           x         m                      x          x            x           ",
   "     x!            !x           x              xxxxx             x          x!!!!!!!!!!!!x           ",
   "     x!            !x           x     xxx                        x          xxxxxxxxxxxxxx           ",
   "     x!xxxx!!!!!!!!!x           x                                x                                   ",
   "     xxxxxxxxxxxxxxxx           xxxxxxxxxx               xxxxxxxxx                                   ",
   "                                         xxxxxxxxxxxxxxxxx                                           ",
   "                                                                                                     ",
   "                                                                                                     ",
   "                                                                                                     ",
   "                                                                                                     ",
   "             x!!!!!x                                                             x!!!!!x             ",
   "         xxxxxxxvxxxxxxx                                                     xxxxxxxvxxxxxxx         ",
   "        x               x                  4           6                    x               x        ",
   "       x                 x                       @                         x                 x       ",
   "      x                   x                                               x                   x      ",
   "     x 6                 5 x             xxxxxxxxxxxxxxxxx               x 5                 4 x     ",
   "      x                   x              xo     o o o   ox                x                   x      ",
   "       x    xxx   xxx    x               x o o o  o o o ox                 x    xxx   xxx    x       ",
   "        x!!!!!!!!!!!!!!!x                x  o o   o o   ox                  x!!!!!!!!!!!!!!!x        ",
   "         xxxxxxxxxxxxxxx                 x               x                   xxxxxxxxxxxxxxx         ",
   "                                         x               x                                           ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                     ",
   "                                                                                                     "],
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
